### ISSUE TITLE
Resource zabbix_host fails when there's a host with no interface type 1

### ISSUE THREAD

**Issue by ludimax** [voxpupuli/puppet-zabbix#660]
https://github.com/voxpupuli/puppet-zabbix/blob/dce7c924109473866f88e316740627e670f6e237/lib/puppet/provider/zabbix_host/ruby.rb#L18

This fails when there's a host with no interface which has 'type' with value 1. 

```
Error: Could not run: undefined method `[]' for nil:NilClass
/opt/puppetlabs/puppet/cache/lib/puppet/provider/zabbix_host/ruby.rb:19:in `block in instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/zabbix_host/ruby.rb:17:in `map'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/zabbix_host/ruby.rb:17:in `instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1199:in `block in instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1198:in `collect'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1198:in `instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/resource/ral.rb:24:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:299:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:228:in `find_or_save_resources'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:142:in `block in main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:137:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:390:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:382:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:710:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:382:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```
 
Example from Zabbix API:
```
 {
            "hostid": "10344",
            "host": "<hostname>",
            "proxy_hostid": "10263",
            "groups": [
                {
                    "groupid": "18",
                    "name": "<groupname>"
                }
            ],
            "parentTemplates": [
                {
                    "host": "Template OS Linux SNMPv2",
                    "templateid": "10248"
                }
            ],
            "interfaces": [
                {
                    "interfaceid": "48",
                    "type": "2",
                    "main": "1",
                    "ip": "<ip>",
                    "port": "161",
                    "useip": "1"
                }
            ]
        }
```

**Comment by Fabian1976** [comment]
Any progress on this? I ran into the same issue. It is perfectly fine to have hosts with only a SNMP interface (Firewall/Switch).

**Comment by aclarkee** [comment]
Ran into this today, had to deny the zabbix api user from accessing the affected resources in zabbix. Providing the user has no access to the resources, you wont get the error. Obviously means you can't manage the resources in puppet using this module as well, until this is fixed.

**Comment by igalic** [comment]
@aclarkee thanks for tracing this down
hopefully somebody can make sense of this and patch it
